CREATE DATABASE NASA_APOD_DB;
GO

USE NASA_APOD_DB;
GO

CREATE TABLE APOD
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Date DATE NOT NULL,
    Title NVARCHAR(500) NOT NULL,
    Explanation NVARCHAR(MAX) NULL,
    Url NVARCHAR(1000) NOT NULL,
    MediaType NVARCHAR(50) NULL,
    ServiceVersion NVARCHAR(50) NULL,
    SavedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT UQ_APOD_Date UNIQUE (Date)
);
GO